package cc.android.photooverlay;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Locale;

import cc.lib.android.EmailHelper;
import cecc.android.lib.PagedFormExporter;
import android.net.Uri;
import android.util.Log;
import android.widget.ImageView;

public class FormExport extends PagedFormExporter {

	private final Form form;
	private final SimpleDateFormat fmt = new SimpleDateFormat("EEEE MMMM d, yyyy", Locale.getDefault());
	private boolean hasCommentsPage = false;
	
	FormExport(BaseActivity activity, Form form, Signature [] signatures) {
		super(activity, signatures);
		this.form = form;
		int numPages = 1;
		if (form.comments != null && form.comments.length() > 0) {
			hasCommentsPage=true;
			numPages++;
		}
		if (signatures.length > 0) {
			numPages += (signatures.length-1) / 3 + 1;
		}
		setNumPages(numPages);
	}

	@Override
	protected void genPage(int pageNum, Signature[] signatures) {
		if (pageNum == 0) {
			mainPage();
		} else if (pageNum == 1 && hasCommentsPage) {
			commentsPage();
		} else {
			signaturesPage(signatures, (pageNum-(hasCommentsPage ? 2 : 1))*3);
		}
		Log.d("HTML Page " + pageNum, html.toString());
	}

	@Override
	protected void onEmailAttachmentReady(File attachment) {
		if (BuildConfig.DEBUG && attachment.getAbsolutePath().endsWith(".jpg")) {
			ImageView iv = new ImageView(getActivity());
			iv.setImageURI(Uri.fromFile(attachment));
			((BaseActivity)getActivity()).newDialogBuilder().setTitle("Preview").setView(iv).show();
		} else
			EmailHelper.sendEmail(getActivity(), attachment, null, getActivity().getString(R.string.emailSubjectSignedReport), getActivity().getString(R.string.email_body_signed_form));		
	}
	
	private void header() {
		header("Pressure Test Report", fmt.format(form.editDate));
		beginTable(0);
		entry("Cusomter:", form.customer);
		entry("Project:", form.project);
		entry("System:", form.system);
		entry("Location:", form.location);
		entry("Installer:", form.inspector);
		endTable();
		beginTable(100);
		entry("Plan:", form.plan, "Spec:", form.spec, "Type:", form.type);
		endTable();
	}
	
	@Override
	protected String getFooter(){
		return "Generated by Pressure Test Utility - ceccsolutions.com";
	}
	
	private void commentsPage() {
		start();
		header();
		entry("Comments", "");
		html.append("<br/><h3>Comments</h3>\n").append(form.comments).append("\n");
		end();
	}
	
	private void mainPage() {
		start();
		header();

		BaseActivity activity = (BaseActivity)getActivity();
		if (form.passed) {
			html.append("</br><b><font color=\"green\">PASSED</font></b>\n");
		} else {
			html.append("</br><b><font color=\"red\">FAILED</font></b>\n");
		}
		
		html.append("<br/><table width=\"100%\">\n");
		html.append("<tr>\n");
		final int dim = Math.round((float)BaseActivity.IMAGE_CAPUTE_DIM / activity.getResources().getDisplayMetrics().density);

		for (int i=0; i<3; i++) {
			html.append("<td>\n");
			if (form.imagePath[i] != null) {
				Uri uri = Uri.fromFile(new File(activity.getImagesPath(), form.imagePath[i]));
				html.append(String.format("<img width=\"%d\" height=\"%d\" src=\"%s\">\n", dim, dim, uri.toString()));//.append("\">\n");
				//html.append(String.format("<img src=\"%s\">\n", uri.toString()));//.append("\">\n");
			} else {
				html.append(String.format("<img width=\"%d\" height=\"%d\" src=\"\" alt=\"No Image\"/>\n", dim, dim));
				//html.append("<img src=\"\" alt=\"No Image\"/>\n");
			}
			html.append("</td>\n");
		}
		
		html.append("</tr><tr>\n");
		for (int i=0; i<3; i++) {
			html.append("<td>\n");
			if (form.imageMeta[i] != null) {
				html.append(form.imageMeta[i]);
			}
			html.append("</td>\n");
		}
		html.append("</tr></table>\n");
		end();
	}

	private void signaturesPage(Signature [] signatures, int offset) {
		start();
		header();
		
		int count = 0;
		for (int i=offset; i<signatures.length; i++) {
			if (count ++ == 3)
				break;
			Signature s = signatures[i];
			html.append("</br><table width=\"100%\"><tr>\n");
			html.append("<td width=\"50%\">");
			html.append(s.fullName == null || s.fullName.isEmpty() ? "Not Specified" : s.fullName).append("</td>\n");
			html.append("<td align=\"right\" width=\"50%\">").append(fmt.format(s.date)).append("</td>\n");
			html.append("</tr></table>");
//			html.append("</br>").append(s.fullName).append("     ").append(fmt.format(s.date));
			Uri uri = Uri.fromFile(s.signatureFile);
			int imgWid = Math.round((float)getWidth() / getActivity().getResources().getDisplayMetrics().density);
			html.append("</br><img width=\"" + imgWid + "\" src=\"").append(uri.toString()).append("\">\n");
		}
		end();
	}

	
}
