apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

dependencies {
    api project(':GameLibrary')
    implementation "androidx.preference:preference:1.2.1"
    implementation 'com.google.android.material:material:1.12.0'
}

android {
    defaultConfig {
	    minSdkVersion project.myMinSdkVersion.toInteger()
        targetSdkVersion project.myTargetSdkVersion
        versionCode 1
	    versionName '1.0.0'
    }

    buildFeatures {
        dataBinding true
        viewBinding true
    }
}