package cc.applets.soc;

public enum MenuState {

	MENU_START,
	MENU_CHOOSE_NUM_PLAYERS,
	MENU_CHOOSE_COLOR,
	MENU_GAME_SETUP,
	MENU_PLAY_GAME,
    MENU_CONNECT_HOST,
    MENU_NETWORK,
	MENU_CONFIG_BOARD,
	MENU_CHOOSE_DEFAULT_BOARD_SIZE,
	MENU_CHOOSE_CUSTOM_BOARD_SIZE, 
	MENU_DEBUGGING,
	MENU_DEBUGAI
	
}
