apply plugin: 'java-library'
apply plugin: 'kotlin'

dependencies {
    implementation project(':GameLibrary')
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
            //, '../GameLibrary/src']
            //exclude '**/swing/**'
            //exclude '**/skunkworks/**'
        }

        resources {
            srcDirs = ['resources'];
        }
    }
}

