package cc.lib.zombicide

import cc.lib.annotation.Keep

@Keep
enum class ZState {
    INIT,
    BEGIN_ROUND,  // reset enchantments
    SPAWN,
    PLAYER_STAGE_CHOOSE_CHARACTER,
    PLAYER_STAGE_CHOOSE_CHARACTER_ACTION,
    PLAYER_STAGE_CHOOSE_NEW_SKILL,
    PLAYER_STAGE_CHOOSE_KEEP_EQUIPMENT,
    PLAYER_ENCHANT_SPEED_MOVE,
    PLAYER_STAGE_CHOOSE_SPAWN_AREA_TO_REMOVE,
    PLAYER_STAGE_CHOOSE_WEAPON_FROM_DECK,
    PLAYER_STAGE_CHOOSE_VAULT_ITEM,
	PLAYER_STAGE_ORGANIZE,
	PLAYER_STAGE_CHOOSE_FAMILIAR_ACTION,
	ZOMBIE_STAGE
}