plugins {
    id "ca.coglinc.javacc" version "2.4.0"
}

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'ca.coglinc.javacc'
apply plugin: 'kotlin'

sourceSets {
    main {
        java {
            srcDirs = [compileJavacc.outputDirectory, 'src']
        }

        resources {
            srcDirs = ['resources']
        }
    }

    test {
        java {
            srcDirs = ['test']
        }
    }
}

compileJavacc {
    inputDirectory = file('src')
}

tasks.named('compileKotlin') {
    dependsOn 'compileJavacc' // Replace with the actual name of your JavaCC task
}

mainClassName = 'cc.app.fractal.FractalViewer'

dependencies {
    implementation project(':GameLibrary')
    implementation project(':SwingApps')
}

tasks.register('bundleFractalApplication', Jar) {
    group = 'Distribution'
    description = 'Fractal Viewer'
    archiveBaseName.set("FractalViewer")

    dependsOn ':GameLibrary:jar'
    dependsOn ':SwingApps:jar'

    exclude 'cc/applets/**'
    exclude 'cc/game/**'
    exclude 'cc/console/**'
    exclude 'cc/experiments/**'

    from(sourceSets.main.output)

    from {
        configurations.runtimeClasspath
                .filter { it.exists() }
                .collect { it.isDirectory() ? it : zipTree(it) }
    }

    manifest {
        attributes["Main-Class"] = "cc.app.fractal.FractalViewer"
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}


