package cc.fantasy.exception;

public enum ErrorCode {

	USER_ACCOUNT_NOT_ACTIVE,
	PASSWORD_MISMATCH,
	EMPTY_FIELD,
	INVALID_DIRECTORY,
	CANNOT_CREATE_DIRECTORY,
	USERNAME_FIELD_MIN_CHARS_NOT_MET,
	PASSWORD_FIELD_MIN_CHARS_NOT_MET,
	USERNAME_ALREADY_IN_USE,
	PASSWORD_NOT_VALID_FOR_USER,
	USERNAME_NOT_FOUND,
	FRANCHISE_NOT_FOUND,
	INVALID_ID,
    TEAM_NOT_FOUND,
	
}
