package cc.lib.ksp.remote

import cc.lib.ksp.netcmd.INetCommand

/**
 * Created by Chris Caron on 3/21/26.
 * Interfaces will be generated by the remote processor of commands that
 * can be detected by NetCommandProcessor for implementation
 */
interface ISvrExecuteRemote : INetCommand {
	val objId: String
	val returnsResult: Boolean
}