apply plugin: 'java-library'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'kotlin'

dependencies {
    implementation project(':GameLibrary')
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }

    test {
        java {
            srcDirs = ['test']
        }
    }
}

ksp {
    arg("package", "cc.game.dominos.core")
}