apply plugin: 'java-library'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'kotlin'

dependencies {
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlin_coroutine_version"
    api "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    api "com.google.code.gson:gson:$google_json_version"
    api(project(':KSPCommon'))
    ksp(project(':KSPRemote'))
    ksp(project(':KSPReflex'))
    ksp(project(':KSPNetCommand'))
}

sourceSets {
    main {
        java {
            srcDirs = [ 'src', 'apps' ]
        }
        resources {
            srcDirs = [ 'resources' ]
        }
    }

    test {
//        useJUnitPlatform()
        java {
            srcDirs = ['test']
        }

        resources {
            srcDirs = ['resources', 'testResources']
        }
    }

}

ksp {
    arg("net_command_registry_name", "GameLib")
    arg("package", "cc.lib.net")
}
