apply plugin: 'java-library'
apply plugin: 'kotlin'
apply plugin: 'com.google.devtools.ksp'

dependencies {
    implementation project(':GameLibrary')
    ksp(project(":KSPNetCommand"))
    ksp(project(":KSPRemote"))

    evaluationDependsOn(':GameLibrary')
    testImplementation files(project(':GameLibrary').sourceSets.test.output)
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }

    test {
        java {
            srcDirs = ['test']
        }
    }
}

ksp {
    arg("net_command_registry_name", "Zombicide")
    arg("package", "cc.game.zombicide")
}