package cc.game.soc.nety;

public enum CommandType {

    CMD_SET_CLIENT_NAME,
    CMD_SET_PING_FREQ,
    CMD_SET_AVAILABLE_COLORS,
    CMD_SET_PLAYER_NUM,
    CMD_SET_BOARD,
    CMD_SET_COLOR,
    CMD_SET_ROAD,
    CMD_SET_SETTLEMENT,
    CMD_SET_CITY,
    CMD_SET_ROBBER,
    CMD_SET_POINTS,
    CMD_SET_RESOURCE_COUNT,
    CMD_SET_ROAD_LENGTH,
    CMD_SET_DICE,
    CMD_SET_LONGEST_ROAD_PLAYER,
    CMD_SET_LARGEST_ARMY_PLAYER,
    CMD_EDIT_DEVEL_CARD,
    CMD_SET_DEVEL_CARDS_USABLE,
    CMD_INITGAME,
    CMD_SET_NUM_PLAYERS,
    CMD_PRINTINFO,
    
    CMD_ROLL_DICE,
    CMD_CHOOSE_CARDS_FOR_GIVEUP,
    CMD_CHOOSE_COLOR,
	CMD_CHOOSE_MOVE,
	CMD_CHOOSE_ROBBER_CELL,
    CMD_CHOOSE_SETTLEMENT,
    CMD_CHOOSE_ROAD,
}
