package cc.game.soc.nety;

public enum RequestType {

	// Connection reqests
	REQ_PING,
	REQ_CONNECT,
	REQ_DISCONNECT,
	
	// in game requests
    REQ_COLOR,
    REQ_SET_ROAD,
	REQ_SET_SETTLEMENT,
	REQ_BUILD_ROAD,
	REQ_BUILD_SETTLEMENT,
	REQ_BUILD_CITY,
	REQ_DRAW_DEVELOPMENT,
	REQ_MONOPOLY,
	REQ_YEAR_OF_PLENTY,
	REQ_ROAD_BUILDING,
	REQ_VICTORY,
	REQ_ROBBER,
	REQ_SOLDIER,
	REQ_CONTINUE,
	REQ_TRADE,
	REQ_ROLL_DICE,
	REQ_GIVE_UP_CARD,
	REQ_CANCEL,
}
