package cc.lib.zombicide;

public enum ZState {
    INIT,
    BEGIN_ROUND, // reset enchantments
    SPAWN,
    PLAYER_STAGE_CHOOSE_CHARACTER,
    PLAYER_STAGE_CHOOSE_CHARACTER_ACTION,
    PLAYER_STAGE_ORGANIZE_CHOOSE_SLOT,
    PLAYER_STAGE_ORGANIZE_CHOOSE_ITEM,
    PLAYER_STAGE_ORGANIZE_CHOOSE_ACTION,
    //PLAYER_STAGE_CHOOSE_DOOR,
    //PLAYER_STAGE_CHOOSE_ZONE_TO_WALK,
    //PLAYER_STAGE_CHOOSE_ZONE_FOR_BILE,
    PLAYER_STAGE_CHOOSE_NEW_SKILL,
    //PLAYER_STAGE_CHOOSE_ZONE_TO_IGNITE,
    ZOMBIE_STAGE,
    ;

}