---------------------------------------------
-- USER TABLE
---------------------------------------------
CREATE TABLE FAN_USER_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(128),
	LAST_NAME VARCHAR(128),
	USER_NAME VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	ACCESS VARCHAR(64),
	EMAIL VARCHAR(128),
	ACTIVE CHAR(1),
	LAST_LOGIN DATE	
);

CREATE SEQUENCE FAN_USER_ID START WITH 100000;

---------------------------------------------
-- FRANCHISE TABLE
---------------------------------------------
CREATE TABLE FAN_FRACHISE_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(128) NOT NULL,
	CATEGORY VARCHAR(128),
	ACTIVE CHAR(1)
);

CREATE SEQUENCE FAN_FRANCHISE_ID START WITH 1000;

---------------------------------------------
-- LEAGUE TABLE
---------------------------------------------
CREATE TABLE FAN_LEAGUE_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(128) NOT NULL,
	USER_ID INTEGER NOT NULL,
	FRANCHISE_ID INTEGER NOT NULL,
	MAX_PLAYERS INTEGER,
	CREATED DATE DEFAULT SYSDATE,
	DRAFT DATE NOT NULL,
	ENDING DATE NOT NULL,
	UPDATED DATE NOT NULL,
);

CREATE SEQUENCE FAN_LEAGUE_ID START WITH 5000;

---------------------------------------------
-- TEAM TABLE
---------------------------------------------
CREATE TABLE FAN_TEAM_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(128) NOT NULL,
	USER_ID INTEGER NOT NULL,
	POINTS INTEGER,
	LEAGUE_ID INTEGER NOT NULL,
);

CREATE SEQUENCE FAN_TEAM_ID START WITH 10000;
	
---------------------------------------------
-- PLAYER TABLE (many-to-one with with franchise)
---------------------------------------------
CREATE TABLE FAN_PLAYER_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(128),
	LAST_NAME VARCHAR(128),
	INFO VARCHAR(128),
	POSITIONS VARCHAR(128),
	STATUS VARCHAR(128)
);

CREATE SEQUENCE FAN_PLAYER_ID START WITH 20000;
	
---------------------------------------------
-- POSITION TABLE (many-to-one with with franchise)
---------------------------------------------
CREATE TABLE FAN_POSITION_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	LONG_NAME VARCHAR(128),
	PLAYER_COLUMN VARCHAR(64),
	SPREADSHEET_FILE VARCHAR(256),
	OMIT_STATS(256)
);
	
CREATE SEQUENCE FAN_POSITION_ID START WITH 30000;

---------------------------------------------
-- STAT TABLE 
---------------------------------------------
CREATE TABLE FAN_STAT_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(128)
);

CREATE SEQUENCE FAN_STAT_ID START WITH 40000;

---------------------------------------------
-- LEAGUE STAT TABLE 
---------------------------------------------
CREATE TABLE FAN_LEAGUE_STAT_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	MULTIPLIER NUMBER,
);

CREATE SEQUENCE FAN_LEAGUE_STAT_ID START WITH 50000;

---------------------------------------------
-- LEAGUE POSITION TABLE 
---------------------------------------------
CREATE TABLE FAN_LEAGUE_POSITION_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	POSITION_ID INTEGER NOT NULL,
	NUM INTEGER,
);

CREATE SEQUENCE FAN_LEAGUE_POSITION_ID START WITH 60000;

---------------------------------------------
-- TEAM PLAYER TABLE 
---------------------------------------------
CREATE TABLE FAN_TEAM_PLAYER_T (
	ID INTEGER NOT NULL PRIMARY KEY,
	PLAYER_ID INTEGER NOT NULL,
	POSITION VARCHAR(32) NOT NULL,
	RANK INTEGER,
);

CREATE SEQUENCE FAN_TEAM_PLAYER_ID START WITH 70000;

-- Create the join tables

CREATE TABLE FAN_FRANCHISE_PLAYER_T (
	FRANCHISE_ID INTEGER NOT NULL,
	PLAYER_ID INTEGER NOT NULL
);

CREATE TABLE FAN_FRANCHISE_POSIITON_T (
	FRANCHISE_ID INTEGER NOT NULL,
	POSITION_ID INTEGER NOT NULL
);

CREATE TABLE FAN_POSITION_STAT_T (
	POSITION_ID INTEGER NOT NULL,
	STAT_ID INTEGER NOT NULL
);

CREATE TABLE FAN_TEAM_TEAMPLAYER_T (
	TEAM_ID INTEGER NOT NULL,
	TEAM_PLAYER_ID INTEGER NOT NULL
);

CREATE TABLE FAN_LEAGUEPOSITION_LEAGUESTAT_T (
	LEAGUE_POSITION_ID INTEGER NOT NULL,
	LEAGUE_STAT_ID INTEGER NOT NULL
);