/* Generated By:JavaCC: Do not edit this line. EvaluatorConstants.java */
package cc.app.fractal.evaluator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EvaluatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNC = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int DOUBLE = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int REAL = 16;
  /** RegularExpression Id. */
  int IMAG = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "<FUNC>",
    "<NUM>",
    "<DOUBLE>",
    "<INT>",
    "<REAL>",
    "<IMAG>",
    "\"[\"",
    "\",\"",
    "\"i\"",
    "\"]\"",
    "\"Z0\"",
    "\"Z\"",
    "\"E\"",
    "\"PI\"",
    "\"X\"",
    "\"Y\"",
    "\"C\"",
    "\"A\"",
    "\"B\"",
  };

}
