apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

repositories {
    maven {
        url 'https://www.hive2hive.org'
    }
}

dependencies {
    api(project(':GameLibrary'))
    api(project(':AndroidGameLibrary'))
}

android {

    namespace = "cc.lib.mp.android"
    defaultConfig {
        targetSdkVersion project.myTargetSdkVersion
        minSdkVersion project.myMinSdkVersion
        targetSdkVersion project.myTargetSdkVersion
        testInstrumentationRunner project.androidTestRunner
    }

    compileOptions {
        sourceCompatibility project.sourceCompatibility
        targetCompatibility project.targetCompatibility
    }

    compileSdk project.myCompileSdkVersion.toInteger()
    //buildToolsVersion project.myBuildToolsVersion

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java {
                srcDirs = ['src']
            }
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            aidl.srcDirs = ['src']
        }

        androidTest {
            java.srcDirs = ['androidTest']
        }

    }

}